# Generated by Django 2.2 on 2019-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=500)),
                ('logo', models.FileField(upload_to='')),
                ('mission', models.CharField(max_length=500)),
                ('vision', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('patron', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_head', models.CharField(max_length=100)),
                ('sub_head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_cover', models.FileField(upload_to='')),
                ('staff_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
